### ISSUE TITLE
openapi to jsonschema

### ISSUE THREAD

**Issue by jayvdb** [zlqm/openapi-toolset#1]
The logic in `strict_schema` doesnt descend into the components (i.e. referenced by `$ref`) and recurse as necessary to do a complete conversion of openapi to jsonschema.

As a result I am seeing

```
mismatch None is not of type 'string'

Failed validating 'type' in schema['items']['properties']['headerImage']:
    {'format': 'uri', 'nullable': True, 'type': 'string'}

On instance[0]['headerImage']:
    None
```

I tried to quickly hack a fix using https://github.com/pglass/py-openapi-schema-to-json-schema , but it also doesnt handle complex openapi schema.
Mine is generated by https://github.com/tfranzel/drf-spectacular

https://github.com/instrumenta/openapi2jsonschema/issues/24 says that tool doesnt do it either, but a comment there says that https://github.com/p1c2u/openapi-core works correctly.

It also has some Django helpers https://github.com/p1c2u/openapi-core/blob/master/README.rst#django

**Comment by jayvdb** [comment]
https://github.com/pglass/py-openapi-schema-to-json-schema/pull/9 shows that library does work, and could be used to do the conversion to jsonschema if you wanted to keep going down that path.  Without my PR, it can still be used if this middleware gave it all of the schema objects within the openapi spec.  Unfortunately there a *lots* of places that schema exist, so I think it makes more sense to convert the entire document once.

**Comment by zlqm** [comment]
> The logic in `strict_schema` doesnt descend into the components (i.e. referenced by `$ref`) and recurse as necessary to do a complete conversion of openapi to jsonschema.

i have submit a commit, hope this [commit](https://github.com/zlqm/openapi-toolset/commit/c0e0c18f15fdc582f23696c75375ae91d5c2ec15) can solved the problem. :)

**Comment by jayvdb** [comment]
It sort of did solve the problem, however many *logic* exceptions occur in the openapi -> jsonschema , when the openapi doesnt contain what the logic expects.  Irrespective of whether the openapi spec is properly formed, Django middleware should not create new exceptions unless explicitly requested by the implementor.

#3 tidies that up, and after that it is able to the endpoints in my schema which I have tested so far.
