### ISSUE TITLE
Fetch doc from a URL

### ISSUE THREAD

**Issue by jayvdb** [zlqm/openapi-toolset#7]
Many sites use a generator, and dont use a static file. e.g. drf-yasg, drf-spectacular, or django-rest-frameworks own schema generator.

Or they upload their spec to a public server so it is maintained externally.

It would be helpful for the spec to be loaded on started from a URL, and for it to support relative URLs or full URLs.

**Comment by zlqm** [comment]
feature added in this commit [add feature: spec from url](https://github.com/zlqm/openapi-toolset/commit/25e8a9fb1473489d0a213b6a359c31ce09510aa8)
